[server]
runOnSave = true
headless = false

[theme]
primaryColor = "#98B82A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#75787B"
textColor = "#262730"
font = "sans serif"

[layout]
wide = true 